# Generated by Django 2.0.7 on 2018-11-02 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, max_length=200, null=True, upload_to='account/avatar', verbose_name='头像')),
                ('github_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='GitHub id')),
                ('new_notice', models.BooleanField(default=False, verbose_name='新的通知')),
                ('read_notice', models.DateTimeField(auto_now_add=True, verbose_name='已读通知')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
