# Generated by Django 2.1.3 on 2018-11-30 16:31

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    from account.models import Profile
    from tools.base import update_model
    ps = Profile.objects.select_related('user').all()
    for p in ps:
        if not p.github_url:
            update_model(p, **{'github_url': 'https://github.com/' + p.user.username})


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='GitHub 个人主页'),
        ),
        migrations.RunPython(migrate_data)
    ]
