# Generated by Django 2.1.3 on 2018-11-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='GitHub 个人主页'),
        ),
    ]
