# Generated by Django 2.1.3 on 2018-12-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-pub_date'], name='blog_articl_pub_dat_86c034_idx'),
        ),
    ]
