# Generated by Django 2.1.3 on 2018-12-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20181205_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.ArticleComment', verbose_name='一级评论'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['-time'], name='comment_art_time_35da82_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecommentreply',
            index=models.Index(fields=['time'], name='comment_art_time_0c0a89_idx'),
        ),
    ]
